#!/bin/bash

java -jar ../Lib/target/Lib-1.0-SNAPSHOT.jar -strategy < ./strategy-tests/1-in.json > results.temp
diff results.temp ./strategy-tests/1-out.json

rm results.temp

java -jar ../Lib/target/Lib-1.0-SNAPSHOT.jar -strategy < ./strategy-tests/2-in.json > results.temp
diff results.temp ./strategy-tests/2-out.json

rm results.temp

java -jar ../Lib/target/Lib-1.0-SNAPSHOT.jar -strategy < ./strategy-tests/3-in.json > results.temp
diff results.temp ./strategy-tests/3-out.json

rm results.temp

java -jar ../Lib/target/Lib-1.0-SNAPSHOT.jar -strategy < ./strategy-tests/4-in.json > results.temp
diff results.temp ./strategy-tests/4-out.json

rm results.temp

java -jar ../Lib/target/Lib-1.0-SNAPSHOT.jar -strategy < ./strategy-tests/5-in.json > results.temp
diff results.temp ./strategy-tests/5-out.json

rm results.temp
